
export const badWords: string[] = [
  'đồ khốn',
  'đồ ngu',
  'đồ điên',
  'chết tiệt',
  'đồ tồi',
  'con đĩ',
  'thằng chó',
  'đm',
  'địt mẹ',
  'vãi lồn',
  'cái lồn',
  'cái cặc',
  'bà nội cha mày',
  'đồ chó đẻ',
  'thằng mặt lồn',
  'con phò',
  'dở hơi',
  'hâm',
  'gàn',
  'ngớ ngẩn',
  'khùng',

  'địt cụ mày',
  'địt mẹ mày',
  'đéo mẹ',
  'đại gia đình mày',
  'đồ súc vật',

  'đồ khốn',
  'đồ ngu',
  'đồ điên',
  'chết tiệt',
  'đồ tồi',
  'fuck you',
  'con đĩ',
  'thằng chó',
  'đm',
  'địt mẹ',
  'vãi lồn',
  'cái lồn',
  'cái cặc',
  'bà nội cha mày',
  'đồ chó đẻ',
  'thằng mặt lồn',
  'con phò',
  'địt cụ mày',
  'địt mẹ mày',
  'đéo mẹ',
  'đồ súc vật',
  'dở hơi',
  'hâm',
  'gàn',
  'ngớ ngẩn',
  'khùng',
  ' địt cụ',
  'địt cha',
  'địt bà',
  'địt ông',
  'địt con mẹ',
  'địt con đĩ',
  'địt cả lò',
  'địt cả nhà',
  'địt cả họ',
  'địt tổ tông',
  'địt tổ sư',
  'đụ mẹ',
  'đụ má',
  'đụ cha',
  'đụ bà',
  'đụ cả nhà mày',
  'đù má',
  'cái lồn mẹ',
  'cái lồn má',
  'cái lồn bà',
  'lồn mẹ mày',
  'lồn chó',
  'lồn điên',
  'cái cặc cha',
  'cặc què',
  'đầu buồi',
  'đầu cặc',
  'óc chó',
  'óc lợn',
  'óc heo',
  'ngu như chó',
  'ngu như bò',
  'ngu như heo',
  'ngu vãi lồn',
  'ngu vãi cặc',
  'ngu vãi đái',
  'khốn nạn',
  'đồ khốn nạn',
  'thằng khốn',
  'con khốn',
  'chó chết',
  'chó má',
  'thứ chó má',
  'đồ chó má',
  'súc sinh',
  'đồ súc sinh',
  'đồ chó săn',
  'đồ mặt lồn',
  'đồ mặt cặc',
  'đồ mặt buồi',
  'cmnr',
  'con mẹ nó rồi',
  'vl',
  'vcl',
  'vãi cả lồn',
  'vãi cả cặc',
  'vãi cả đái',
  'vãi đái',
  'vãi cứt',
  'đkm',
  'dkm',
  'cc',
  'dcm',
  'đcm',
  'dcm',
  'dit me',
  'dũ nghi',
  'dit con me',
  'dit cu may',
  'dit cha may',
  'du ma',
  'du má',
  'vai lon',
  'cai lon',
  'cai cac',
  'oc cho',
  'ngu nhu cho',
  'khon nan',
  'cho chet',
  'suc vat',
  'suc sinh',
  'mat lon',
  'mat cac',
  'thằng mặt cặc',
  'con mặt lồn',
  'đồ mặt chó',
  'đồ vô lại',
  'thứ vô lại',
  'đồ mất dạy',
  'thứ mất dạy',
  'đồ vô học',
  'thứ vô học',
  'đồ đểu',
  'thứ đểu giả',
  'đồ khốn kiếp',
  'thằng khốn kiếp',
  'con khốn kiếp',
  'đồ cặn bã',
  'thứ cặn bã',
  'đồ rác rưởi',
  'thứ rác rưởi',
  'đồ tồi tệ',
  'đồ bỉ ổi',
  'thứ bỉ ổi',
  'đồ hèn hạ',
  'thứ hèn hạ',
  'đồ đê tiện',
  'thứ đê tiện',
  'đồ vô liêm sỉ',
  'thứ vô liêm sỉ',
  'đồ mặt dày',
  'thứ mặt dày',
  'đồ trơ trẽn',
  'thứ trơ trẽn',
  'đồ lợn',
  'thằng lợn',
  'con lợn',
  'đồ bò',
  'đồ trâu',
  'đồ gà',
  'đồ cờ hó',
  'đồ dâm tặc',
  'đồ dâm đãng',
  'đĩ bút',
  'đĩ thỏa',
  'đĩ điếm',
  'con đĩ điếm',
  'thằng đĩ điếm',
  'bà cha mày',
  'bà nội mày',
  'ông nội mày',
  'ông cố mày',
  'bà cố mày',
  'đồ ăn hại',
  'thứ ăn hại',
  'đồ ăn bám',
  'thứ ăn bám',
  'đồ ăn cắp',
  'thứ ăn cắp',
  'đồ ăn trộm',
  'thứ ăn trộm',
  'đồ ăn cướp',
  'thứ ăn cướp',
  'đồ đầu trộm đuôi cướp',
  'thứ đầu trộm đuôi cướp',
  'đồ lừa đảo',
  'thứ lừa đảo',
  'đồ lừa gạt',
  'thứ lừa gạt',
  'đồ gian xảo',
  'thứ gian xảo',
  'đồ xảo trá',
  'thứ xảo trá',
  'đồ phản phúc',
  'thứ phản phúc',
  'đồ phản bội',
  'thứ phản bội',
  'đồ chó săn',
  'thằng chó săn',
  'con chó săn',
  'đồ tay sai',
  'thứ tay sai',
  'đồ bán nước',
  'thứ bán nước',
  'đồ việt gian',
  'thứ việt gian',
  'đồ ngu dốt',
  'thứ ngu dốt',
  'đồ dốt nát',
  'thứ dốt nát',
  'đồ thiểu năng',
  'thứ thiểu năng',
  'đồ thiểu não',
  'thứ thiểu não',
  'đồ bại não',
  'thứ bại não',
  'đồ tâm thần',
  'thứ tâm thần',
  'đồ thần kinh',
  'thứ thần kinh',
  'đồ bệnh hoạn',
  'thứ bệnh hoạn',
  'đồ biến thái',
  'thứ biến thái',
  'đồ khùng điên',
  'thứ khùng điên',
  'đồ dở người',
  'thứ dở người',
  'đồ hâm hấp',
  'thứ hâm hấp',
  'đồ dở hơi',
  'thứ dở hơi',
  'đồ ẩm ương',
  'thứ ẩm ương',
  'đồ ba trợn',
  'thứ ba trợn',
  'đồ bố láo',
  'thứ bố láo',
  'đồ mất nết',
  'thứ mất nết',
  'đồ vô duyên',
  'thứ vô duyên',
  'đồ vô ý thức',
  'thứ vô ý thức',
  'đồ ích kỷ',
  'thứ ích kỷ',
  'đồ hẹp hòi',
  'thứ hẹp hòi',
  'đồ nhỏ nhen',
  'thứ nhỏ nhen',
  'đồ ti tiện',
  'thứ ti tiện',
  'đồ bần tiện',
  'thứ bần tiện',
  'đồ keo kiệt',
  'thứ keo kiệt',
  'đồ bủn xỉn',
  'thứ bủn xỉn',
  'đồ tham lam',
  'thứ tham lam',
  'đồ độc ác',
  'thứ độc ác',
  'đồ tàn nhẫn',
  'thứ tàn nhẫn',
  'đồ nhẫn tâm',
  'thứ nhẫn tâm',
  'đồ vô nhân đạo',
  'thứ vô nhân đạo',
  'đồ vô lương tâm',
  'thứ vô lương tâm',
  'đồ lang sói',
  'thứ lang sói',
  'đồ cầm thú',
  'thứ cầm thú',
  'đồ không bằng cầm thú',
  'thứ không bằng cầm thú',
  'đồ chó ghẻ',
  'thằng chó ghẻ',
  'con chó ghẻ',
  'đồ đầu đường xó chợ',
  'thứ đầu đường xó chợ',
  'đồ bụi đời',
  'thứ bụi đời',
  'đồ du côn',
  'thứ du côn',
  'đồ lưu manh',
  'thứ lưu manh',
  'đồ côn đồ',
  'thứ côn đồ',
  'đồ giang hồ',
  'thứ giang hồ',
  'đồ xã hội đen',
  'thứ xã hội đen',
  'đồ ma cô',
  'thằng ma cô',
  'đồ ma cô dắt gái',
  'đồ ma c bông',
  'đồ mạt hạng',
  'thứ mạt hạng',
  'đồ mạt vận',
  'thứ mạt vận',
  'đồ mạt rệp',
  'thứ mạt rệp',
  'đồ rẻ rách',
  'thứ rẻ rách',
  'đồ giẻ rách',
  'thứ giẻ rách',
  'đồ vứt đi',
  'thứ vứt đi',
  'đồ vô tích sự',
  'thứ vô tích sự',
  'đồ ăn không ngồi rồi',
  'thứ ăn không ngồi rồi',
  'đồ phế vật',
  'thứ phế vật',
  'đồ vô dụng',
  'thứ vô dụng',
  'đồ ăn hại đái nát',
  'đồ ăn hại báo đời',
  'đồ trời đánh',
  'thứ trời đánh',
  'đồ thánh vật',
  'đồ quỷ sứ',
  'đồ yêu ma',
  'đồ yêu quái',
  'đồ yêu tinh',
  'đồ ma quỷ',
  'đồ quỷ ma',
  'đồ đầu lâu xó bếp',
  'đồ âm binh',
  'thứ âm binh',
  'đồ chết bằm',
  'thứ chết bằm',
  'đồ chết đâm',
  'thứ chết đâm',
  'đồ chết chém',
  'thứ chết chém',
  'đồ chết giẫm',
  'thứ chết giẫm',
  'đồ chết toi',
  'thứ chết toi',
  'đồ chết dịch',
  'thứ chết dịch',
  'đồ chết yểu',
  'thứ chết yểu',
  'đồ chết non',
  'thứ chết non',
  'đồ chết không toàn thây',
  'đồ chết bờ chết bụi',
  'đồ chết không nhắm mắt',
  'cút',
  'biến',
  'xéo',
  'lượn',
  'phắn',
  'cút mẹ mày đi',
  'biến mẹ mày đi',
  'cút xéo',
  'cút ngay',
  'biến ngay',
  'lượn cho nước nó trong',
  'phắn cho nhanh',
  'địt mẹ cút',
  'đụ má biến',
  'đừng có lảng vảng trước mặt tao',
  'đừng có vác mặt đến đây',
  'mặt dày mày vác mặt đến đây làm gì',
  'đồ mặt mo',
  'thằng mặt mo',
  'con mặt mo',
  'đồ mặt thớt',
  'thằng mặt thớt',
  'con mặt thớt',
  'đồ mặt mẹt',
  'thằng mặt mẹt',
  'con mặt mẹt',
  'đồ mặt sứa',
  'thằng mặt sứa',
  'con mặt sứa',
  'đồ mặt cóc',
  'thằng mặt cóc',
  'con mặt cóc',
  'đồ mặt rỗ',
  'thằng mặt rỗ',
  'con mặt rỗ',
  'đồ mặt sẹo',
  'thằng mặt sẹo',
  'con mặt sẹo',
  'đồ mặt mụn',
  'thằng mặt mụn',
  'con mặt mụn',
  'đồ mặt nám',
  'con mặt nám',
  'đồ xấu xí',
  'thứ xấu xí',
  'đồ xấu ma chê quỷ hờn',
  'đồ xấu xúc phạm người nhìn',
  'đồ xấu như chó',
  'đồ xấu như ma',
  'đồ xấu như quỷ',
  'đồ xấu kinh hoàng',
  'đồ xấu tàn tệ',
  'đồ xấu đau xấu đớn',
  'đồ béo như lợn',
  'đồ béo như heo',
  'đồ béo như trâu',
  'đồ béo ú',
  'đồ béo phì',
  'đồ gầy như que củi',
  'đồ gầy như ma đói',
  'đồ gầy như cò hương',
  'đồ gầy trơ xương',
  'đồ đen như cột nhà cháy',
  'đồ đen như than',
  'đồ đen như mọi',
  'đồ lùn',
  'đồ lùn tịt',
  'đồ chân ngắn',
  'đồ nấm lùn di động',
  'đồ cao như sào',
  'đồ cao kều',
  'đồ lác',
  'đồ chột',
  'đồ mù',
  'đồ điếc',
  'đồ câm',
  'đồ què',
  'đồ què quặt',
  'đồ tàn tật',
  'đồ tàn phế',
  'đồ phế nhân',
  'đồ thần kinh không ổn định',
  'đồ thần kinh có vấn đề',
  'đồ tâm thần phân liệt',
  'đồ hoang tưởng',
  'đồ tự kỷ',
  'đồ trầm cảm',
  'đồ thần kinh giả',
  'đồ điên giả',
  'đồ ngu giả',
  'đồ ngây thơ vô số tội',
  'đồ hai mặt',
  'đồ giả nhân giả nghĩa',
  'đồ giả tạo',
  'đồ lật lọng',
  'đồ tráo trở',
  'đồ ba phải',
  'đồ gió chiều nào che chiều ấy',
  'đồ không có lập trường',
  'đồ đâm sau lưng',
  'đồ chơi bẩn',
  'đồ chơi xấu',
  'đồ hèn',
  'thằng hèn',
  'con hèn',
  'đồ nhát gan',
  'thứ nhát gan',
  'đồ nhát như thỏ đế',
  'đồ yếu đuối',
  'thứ yếu đuối',
  'đồ nhu nhược',
  'thứ nhu nhược',
  'đồ bất tài',
  'thứ bất tài',
  'đồ bất lực',
  'thứ bất lực',
  'đồ vô năng',
  'thứ vô năng',
  'đồ bất hiếu',
  'thứ bất hiếu',
  'đồ bất nghĩa',
  'thứ bất nghĩa',
  'đồ bất nhân',
  'thứ bất nhân',
  'đồ bất trung',
  'thứ bất trung',
  'đồ bất tín',
  'thứ bất tín',
  'đồ lăng loàn',
  'con lăng loàn',
  'đồ lẳng lơ',
  'con lẳng lơ',
  'đồ trắc nết',
  'con trắc nết',
  'đồ dâm phụ',
  'con dâm phụ',
  'đồ dâm nữ',
  'con dâm nữ',
  'đồ dâm tặc',
  'thằng dâm tặc',
  'đồ dê xồm',
  'thằng dê xồm',
  'đồ dê cụ',
  'thằng dê cụ',
  'cl',
  'clmm',
  'clm',
  'dm clm',
'đồ yếu sinh lý',
'thằng yếu sinh lý',
'đồ bất lực',
'thằng bất lực',
'đồ pê đê',
'thằng pê đê',
'đồ đồng tính',
'đồ ái nam ái nữ',
'đồ bóng lộ',
'thằng bóng lộ',
'đồ bóng kín',
'thằng bóng kín',
'đồ les',
'con les',
'đồ les cặp',
'đồ gay',
'thằng gay',
'đồ gay lọ',
'đồ gay kín',
'đồ gay lộ',
'đồ LGBT',
'đồ giới tính thứ ba',
'đồ không nam không nữ',
'đồ nửa nạc nửa mỡ',
'đồ tạp pí lù',
'thứ tạp pí lù',
'đồ hổ lốn',
'thứ hổ lốn',
'đồ bá vơ',
'thứ bá vơ',
'đồ tào lao',
'thứ tào lao',
'đồ vớ vẩn',
'thứ vớ vẩn',
'đồ linh tinh',
'thứ linh tinh',
'đồ lăng nhăng',
'thứ lăng nhăng',
'đồ nhảm nhí',
'thứ nhảm nhí',
'đồ ruồi bu',
'thứ ruồi bu',
'đồ kền kền',
'thứ kền kền',
'đồ đỉa đói',
'thứ đỉa đói',
'đồ sâu bọ',
'thứ sâu bọ',
'đồ giòi bọ',
'thứ giòi bọ',
'đồ chấy rận',
'thứ chấy rận',
'đồ cặn bã xã hội',
'thứ cặn bã xã hội',
'đồ ung nhọt xã hội',
'thứ ung nhọt xã hội',
'đồ con sâu làm rầu nồi canh',
'đồ phá gia chi tử',
'thằng phá gia chi tử',
'đồ báo đời',
'thằng báo đời',
'con báo đời',
'đồ báo cô',
'thằng báo cô',
'con báo cô',
'đồ báo cha báo mẹ',
'đồ của nợ',
'thứ của nợ',
'đồ nợ đời',
'thứ nợ đời',
'đồ oan gia',
'thứ oan gia',
'đồ nghiệp chướng',
'thứ nghiệp chướng',
'đồ sao chổi',
'thứ sao chổi',
'đồ xui xẻo',
'thứ xui xẻo',
'đồ ám quẻ',
'thứ ám quẻ',
'đồ hãm tài',
'thứ hãm tài',
'đồ hãm lồn',
'con hãm lồn',
'đồ hãm cặc',
'thằng hãm cặc',
'đồ dái vặt',
'thằng dái vặt',
'đồ dái ngựa',
'thằng dái ngựa',
'đồ dái bò',
'thằng dái bò',
'đồ tinh trùng thượng não',
'thằng tinh trùng thượng não',
'đồ tinh trùng khuyết tật',
'đồ não tàn',
'thứ não tàn',
'đồ não phẳng',
'thứ não phẳng',
'đồ não ngắn',
'thứ não ngắn',
'đồ không não',
'thứ không não',
'đồ não cá vàng',
'thứ não cá vàng',
'đồ não chó',
'thứ não chó',
'đồ não lợn',
'thứ não lợn',
'đồ óc cứt',
'thứ óc cứt',
'đồ óc bằng quả nho',
'đồ óc teo',
'đồ óc bã đậu',
'thứ óc bã đậu',
'đồ óc bò',
'thứ óc bò',
'đồ óc trâu',
'thứ óc trâu',
'đồ óc đất',
'thứ óc đất',
'đồ óc sỏi',
'thứ óc sỏi',
'đồ óc đá',
'thứ óc đá',
'đồ ngu học',
'thằng ngu học',
'con ngu học',
'đồ học ngu',
'thằng học ngu',
'con học ngu',
'đồ dốt đặc cán mai',
'đồ dốt như bò',
'đồ dốt không biết chữ',
'đồ mù chữ',
'thứ mù chữ',
'đồ nhà quê',
'thứ nhà quê',
'đồ quê một cục',
'đồ hai lúa',
'đồ bần nông',
'thứ bần nông',
'đồ dân trí thấp',
'thứ dân trí thấp',
'đồ vô văn hóa',
'thứ vô văn hóa',
'đồ mọi rợ',
'thứ mọi rợ',
'đồ man di',
'thứ man di',
'đồ man rợ',
'thứ man rợ',
'đồ bán khai',
'thứ bán khai',
'đồ tiền sử',
'thứ tiền sử',
'đồ cổ lỗ sĩ',
'thứ cổ lỗ sĩ',
'đồ lạc hậu',
'thứ lạc hậu',
'đồ nhà binh',
'thứ nhà binh',
'đồ thất học',
'thứ thất học',
'đồ đầu đất',
'thằng đầu đất',
'con đầu đất',
'đồ đầu bò',
'thằng đầu bò',
'con đầu bò',
'đồ đầu trâu mặt ngựa',
'đồ mặt người dạ thú',
'đồ thú đội lốt người',
'đồ ác quỷ',
'đồ ác ma',
'đồ ác phụ',
'con ác phụ',
'đồ ác bá',
'thằng ác bá',
'đồ đầu gấu',
'thằng đầu gấu',
'con đầu gấu',
'đồ anh chị',
'đồ đại ca',
'đồ đại tỷ',
'đồ giang hồ mạng',
'đồ anh hùng bàn phím',
'đồ mõm',
'đồ mồm chó vó ngựa',
'đồ mồm loa mép giải',
'đồ mồm thối',
'đồ mồm hôi',
'đồ mồm rộng',
'đồ mồm to',
'đồ lắm mồm',
'đồ nhiều chuyện',
'đồ bà tám',
'đồ bà chằn',
'con bà chằn',
'đồ sư tử Hà Đông',
'con sư tử Hà Đông',
'đồ la sát',
'con la sát',
'đồ chằn tinh',
'con chằn tinh',
'đồ yêu nữ',
'con yêu nữ',
'đồ yêu râu xanh',
'thằng yêu râu xanh',
'đồ háo sắc',
'thằng háo sắc',
'đồ háo dâm',
'thằng háo dâm',
'đồ mê gái',
'thằng mê gái',
'đồ mê trai',
'con mê trai',
'đồ lụy tình',
'đồ cuồng dâm',
'đồ cuồng ghen',
'đồ ghen tuông bệnh hoạn',
'đồ sở khanh',
'thằng sở khanh',
'đồ bạc tình',
'thứ bạc tình',
'đồ bạc nghĩa',
'thứ bạc nghĩa',
'đồ phụ tình',
'thứ phụ tình',
'đồ phụ bạc',
'thứ phụ bạc',
'đồ lăng nhăng',
'thằng lăng nhăng',
'con lăng nhăng',
'đồ mèo mả gà đồng',
'đồ trốn chúa lộn chồng',
'con trốn chúa lộn chồng',
'đồ đàng điếm',
'con đàng điếm',
'đồ lẳng lơ ong bướm',
'con lẳng lơ ong bướm',
'đồ ve vãn',
'con ve vãn',
'đồ mồi chài',
'con mồi chài',
'đồ lừa tình',
'thằng lừa tình',
'con lừa tình',
'đồ đào mỏ',
'con đào mỏ',
'đồ thực dụng',
'con thực dụng',
'đồ hám tiền',
'con hám tiền',
'đồ hám danh',
'con hám danh',
'đồ hám lợi',
'con hám lợi',
'đồ hám fame',
'con hám fame',
'đồ sống ảo',
'con sống ảo',
'đồ câu like',
'đồ câu view',
'đồ làm màu',
'đồ màu mè',
'đồ hoa hòe hoa sói',
'đồ lòe loẹt',
'đồ diêm dúa',
'đồ sến súa',
'đồ quê mùa',
'đồ lỗi thời',
'đồ cổ hủ',
'đồ bảo thủ',
'đồ gia trưởng',
'thằng gia trưởng',
'đồ độc đoán',
'đồ độc tài',
'đồ phát xít',
'đồ chuyên quyền',
'đồ áp đặt',
'đồ bảo thủ cố chấp',
'đồ cứng đầu',
'đồ bướng bỉnh',
'đồ lì lợm',
'đồ lỳ',
'đồ ương bướng',
'đồ ngang ngược',
'đồ ngỗ ngược',
'đồ hỗn láo',
'đồ hỗn xược',
'đồ láo toét',
'đồ láo lếu',
'đồ vô lễ',
'đồ vô phép',
'đồ không coi ai ra gì',
'đồ tự cao tự đại',
'đồ tự mãn',
'đồ tự phụ',
'đồ tự kiêu',
'đồ kiêu ngạo',
'đồ ngạo mạn',
'đồ hống hách',
'đồ kênh kiệu',
'đồ chảnh',
'đồ chảnh chó',
'con chảnh chó',
'thằng chảnh chó',
'đồ làm phách',
'đồ ra vẻ',
'đồ tinh vi',
'đồ tinh tướng',
'đồ khệnh khạng',
'đồ vênh váo',
'đồ vênh mặt',
'đồ ta đây',
'đồ bố đời',
'thằng bố đời',
'đồ mẹ thiên hạ',
'con mẹ thiên hạ',
'đồ trời con',
'thằng trời con',
'đồ công tử bột',
'thằng công tử bột',
'đồ tiểu thư đài các',
'con tiểu thư đài các',
'đồ cành vàng lá ngọc',
'đồ con ông cháu cha',
'đồ COCC',
'đồ con nhà lính tính nhà quan',
'đồ ỷ thế hiếp người',
'đồ cáo mượn oai hùm',
'đồ chó cậy gần nhà',
'đồ gà cậy gần chuồng',
'đồ ném đá giấu tay',
'đồ đâm bị thóc chọc bị gạo',
'đồ gắp lửa bỏ tay người',
'đồ đổ vỏ',
'thằng đổ vỏ',
'đồ ăn ốc nói mò',
'đồ ăn không nói có',
'đồ đặt điều',
'đồ vu khống',
'đồ vu oan',
'đồ bịa đặt',
'đồ bịa chuyện',
'đồ dựng chuyện',
'đồ nói xấu',
'đồ nói đểu',
'đồ nói móc',
'đồ nói kháy',
'đồ nói xiên nói xỏ',
'đồ châm chọc',
'đồ mỉa mai',
'đồ chửi đổng',
'đồ chửi cha không từ một tiếng',
'đồ chửi như hát hay',
'đồ chửi như tát nước vào mặt',
'đồ ăn cháo đá bát',
'đồ qua cầu rút ván',
'đồ vô ơn',
'đồ vô ơn bội nghĩa',
'đồ vong ơn bội nghĩa',
'đồ vong ân',
'đồ ăn cắp quen tay',
'đồ ngủ ngày quen mắt',
'đồ cờ bạc',
'thằng cờ bạc',
'đồ nghiện ngập',
'thằng nghiện ngập',
'đồ nghiện hút',
'thằng nghiện hút',
'đồ nghiện rượu',
'thằng nghiện rượu',
'đồ nát rượu',
'thằng nát rượu',
'đồ say xỉn',
'đồ bê tha',
'đồ lêu lổng',
'đồ lông bông',
'đồ vô công rồi nghề',
'đồ ăn bám vợ',
'thằng ăn bám vợ',
'đồ ăn bám cha mẹ',
'đồ ăn bám gia đình',
'đồ ăn bám xã hội',
'đồ ký sinh trùng',
'thứ ký sinh trùng',
'đồ sâu mọt',
'thứ sâu mọt',
'đồ sâu dân mọt nước',
'đồ tham quan',
'đồ tham ô',
'đồ tham nhũng',
'đồ ăn hối lộ',
'đồ đút lót',
'đồ quan liêu',
'đồ cửa quyền',
'đồ hách dịch',
'đồ sách nhiễu',
'đồ vòi vĩnh',
'đồ moi tiền',
'đồ ăn chặn',
'đồ ăn bớt',
'đồ ăn quỵt',
'đồ quỵt nợ',
'đồ bùng tiền',
'đồ trốn nợ',
'đồ lừa thầy phản bạn',
'đồ phản thầy',
'đồ phản bạn',
'đồ bán đứng bạn bè',
'đồ bán rẻ lương tâm',
'đồ vô đạo đức',
'thứ vô đạo đức',
'đồ suy đồi đạo đức',
'đồ bại hoại',
'đồ bại hoại nhân cách',
'đồ bại hoại gia phong',
'đồ mất gốc',
'đồ vô gia đình',
'đồ không cha không mẹ',
'đồ trẻ mồ côi',
'đồ đầu đường xó chợ',
'đồ lang thang',
'đồ cơ nhỡ',
'đồ bụi đời',
'đồ tép riu',
'đồ tép riu đầu bạc',
'đồ tép riu đầu xanh',
'đồ vắt mũi chưa sạch',
'đồ hỉ mũi chưa sạch',
'đồ miệng còn hôi sữa',
'đồ con nít',
'đồ trẻ trâu',
'đồ sửu nhi',
'đồ ranh con',
'đồ nhãi ranh',
'đồ nhóc con',
'đồ con hoang',
'đồ súc vật đội lốt người',
'đồ thú tính',
'đồ mất nhân tính',
'đồ cuồng sát',
'đồ giết người không gớm tay',
'đồ máu lạnh',
'thằng máu lạnh',
'đồ sát nhân',
'đồ sát thủ',
'đồ khủng bố',
'đồ tội phạm',
'đồ tù tội',
'đồ có tiền án tiền sự',
'đồ vào tù ra tội',
'đồ cải tạo không tốt',
'đồ ngựa quen đường cũ',
'đồ chứng nào tật nấy',
'đồ giang sơn dễ đổi bản tính khó dời',
'đồ chó không đổi được tính ăn cứt',
'đồ chó dại',
'đồ chó điên',
'đồ chó hoang',
'đồ chó hùa',
'đồ chó hùa a dua',
'đồ a dua',
'đồ a tòng',
'đồ theo đóm ăn tàn',
'đồ ba que',
'đồ ba que xỏ lá',
'đồ ba trợn ba trạo',
'đồ đầu bò đầu bướu',
'đồ đầu trâu mặt ngựa',
'đồ lòng lang dạ sói',
'đồ lòng cá dạ chó',
'đồ lòng muông dạ thú',
'đồ mặt người tim quỷ',
'đồ miệng nam mô bụng một bồ dao găm',
'đồ khẩu phật tâm xà',
'đồ miệng lưỡi thế gian',
'đồ lắm điều',
'đồ lắm lời',
'đồ lắm chuyện',
'đồ rỗi hơi',
'đồ dở người',
'đồ dở ông dở thằng',
'đồ dở dở ương ương',
'đồ nửa mùa',
'đồ học đòi',
'đồ đua đòi',
'đồ trèo cao ngã đau',
'đồ không biết lượng sức mình',
'đồ ảo tưởng sức mạnh',
'đồ ảo tưởng',
'đồ mơ mộng hão huyền',
'đồ viển vông',
'đồ phi thực tế',
'đồ ngu ngốc',
'đồ ngốc nghếch',
'đồ khờ khạo',
'đồ khờ dại',
'đồ ngây ngô',
'đồ ngây thơ',
'đồ tin người',
'đồ cả tin',
'đồ nhẹ dạ',
'đồ dễ dãi',
'con dễ dãi',
'đồ dễ dắt mũi',
'đồ bị dắt mũi',
'đồ bị lợi dụng',
'đồ bị thao túng',
'đồ bù nhìn',
'đồ con rối',
'đồ công cụ',
'đồ tay sai',
'đồ con chốt thí',
'đồ vật hy sinh',
'đồ con cừu non',
'đồ nai tơ',
'đồ gà mờ',
'đồ lơ ngơ',
'đồ ngáo ngơ',
'đồ ngáo',
'đồ ngáo đá',
'thằng ngáo đá',
'đồ phê pha',
'đồ chơi đồ',
'đồ hút chích',
'đồ nghiện',
'đồ con nghiện',
'đồ ăn hại',
'đồ báo hại',
'đồ hại đời',
'đồ hại người',
'đồ gieo rắc tai họa',
'đồ gieo nhân nào gặt quả nấy',
'đồ quả báo',
'đồ nghiệp quật',
'đồ nghiệp tụ vành môi',
'đồ khẩu nghiệp',
'đồ tạo nghiệp',
'đồ nghiệp nặng',
'đồ oan nghiệt',
'đồ oan gia trái chủ',
'đồ khắc tinh',
'đồ quả tạ',
'đồ cục nợ',
'đồ gánh nặng',
'đồ phiền phức',
'đồ rắc rối',
'đồ tai ương',
'đồ tai họa',
'đồ sao quả tạ',
'đồ vận đen',
'đồ số nhọ',
'đồ đen đủi',
'đồ xui tận mạng',
'đồ chết không có chỗ chôn',
'đồ chết không toàn thây',
'đồ chết rục xương',
'đồ chết mục thây',
'đồ chết thối đất',
'đồ chết trôi sông',
'đồ chết cháy',
'đồ chết tươi',
'đồ chết bất đắc kỳ tử',
'đồ chết không đáng tiếc',
'đồ chết cũng đáng',
'đồ đáng đời',
'đồ đáng kiếp',
'đồ kiếp trước ăn ở không ra gì',
'đồ ác giả ác báo',
'đồ gậy ông đập lưng ông',
'đồ tự làm tự chịu',
'đồ tự chuốc họa vào thân',
'đồ ngu thì chết',
'đồ ngu có hạn',
'đồ ngu lâu dốt bền',
'đồ ngu đột xuất',
'đồ ngu có đào tạo',
'đồ ngu có hệ thống',
'đồ ngu bẩm sinh',
'đồ ngu gia truyền',
'đồ ngu không lối thoát',
'đồ ngu không ai bằng',
'đồ ngu vô đối',
'đồ ngu vô cực',
'đồ ngu kinh điển',
'đồ ngu lịch sử',
'đồ ngu vĩnh cửu',
'đồ ngu thiên thu',
'đồ ngu bất tử',
'đồ ngu xuyên lục địa',
'đồ ngu tầm cỡ quốc tế',
'đồ ngu có một không hai',
'đồ ngu có tổ chức',
'đồ ngu được bảo tồn',
'đồ ngu cần được nhân giống',
'đồ ngu cần đưa vào sách đỏ',
'ditmemay',
'djtme',
'djtcu',
'ditba',
'lonme',
'lonma',
'cacc',
'caccha',
'daubuoi',
'daicac',
'occho',
'nguvl',
'nguvcl',
'khonnan',
'chochet',
'choma',
'sucsinh',
'matlon',
'matcac',
'buoi',
'buồi',
'dau buoi',
'đầu buồi',
'cẹc',
'cẹc què',
'lìn',
'cái lìn',
'hãm lìn',
'con hãm lìn',
'dái',
'dái ngựa',
'dái bò',
'hòn dái',
'hai hòn dái',
'đồ dái vặt',
'thằng dái vặt',
'đồ dái to',
'thằng dái to',
'đồ không có dái',
'thằng không có dái',
'đồ đàn bà',
'thằng đàn bà',
'đồ yếu như sên',
'đồ yếu như bún',
'đồ công chúa',
'thằng công chúa',
'đồ hoàng tử',
'đồ tiểu thư',
'đồ mong manh dễ vỡ',
'đồ mít ướt',
'đồ khóc nhè',
'đồ ăn vạ',
'đồ mè nheo',
'đồ nhõng nhẽo',
'đồ làm nũng',
'đồ õng ẹo',
'con õng ẹo',
'đồ lố lăng',
'đồ kệch cỡm',
'đồ lố bịch',
'đồ γραφειοκράτης',
'đồ γραφειοκρατία',
'đồ γαμώ',
'dit',
'djt',
  'đ!t',
  'd!t m3',
'dit me may',
'dit con me may',
'djt con me may',
'dit ca nha may',
'djt ca nha may',
'dit to tong may',
'dit ba doi nha may',
'du ma may',
'du ma nha may',
'đm',
'đcm',
'dkm',
'đờ mờ',
'đờ cờ mờ',
'đờ ca mờ',
'địt con mẹ nó',
'đụ con má nó',
'đù má nó',
'mẹ kiếp',
'má kiếp',
'cha kiếp',
'bà kiếp',
'ông kiếp',
'tổ kiếp',
'chết tiệt mày',
'chết bằm mày',
'chết đâm mày',
'mả mẹ mày',
'mả cha mày',
'mả bà mày',
'mả tổ mày',
'mồ mẹ mày',
'mồ cha mày',
'mồ bà mày',
'mồ tổ mày',
'đào mồ cuốc mả nhà mày lên',
'địt từ dưới lên',
'đụ từ trên xuống',
'lồn mẹ mi',
'cặc cha mi',
'địt bà nội mi',
'địt ông nội mi',
'đụ má mi',
'mẹ mày',
'cha mày',
'bà mày',
'ông mày',
'cụ mày',
'kị mày',
'tổ mày',
'đồ khốn nạn nhà mày',
'đồ chó chết nhà mày',
'đồ súc sinh nhà mày',
'đồ mất dạy nhà mày',
'đồ vô học nhà mày',
'đồ bố láo ăn cắp',
'thứ bố láo ăn cắp',
'đồ đầu trâu mặt ngựa',
'đồ lòng lang dạ sói',
'đồ mặt người dạ thú',
'ngu ơi là ngu',
'ngu không tả nổi',
'ngu hết phần người khác',
'ngu hết thuốc chữa',
'ngu không chừa một ai',
'ngu không đỡ được',
'ngu không thể tả',
'ngu không thể tin được',
'ngu đến thế là cùng',
'ngu tột đỉnh',
'ngu tột độ',
'ngu cực phẩm',
'ngu vô địch',
'ngu bá đạo',
'ngu xuyên tạc',
'ngu phá hoại',
'ngu tàn phá',
'ngu hủy diệt',
'ngu có hệ thống',
'ngu có tổ chức và có đào tạo',
'ngu có chứng chỉ',
'ngu được cấp bằng',
'ngu có thâm niên',
'ngu có kinh nghiệm',
'ngu từ trong trứng',
'ngu từ trong bụng mẹ',
'ngu từ nhỏ đến lớn',
'ngu từ bé đến giờ',
'ngu từ đời ông bà',
'ngu di truyền',
'ngu lây lan',
'ngu mãn tính',
'ngu nan y',
'ngu vô phương cứu chữa',
'ngu bất trị',
'ngu không药 chữa',
'đồ tàn đời',
'đồ mạt kiếp',
'đồ tận thế',
'đồ ngày tàn',
'đồ chết không có đất chôn',
'đồ chết không có người thân',
'đồ chết không có ai thương tiếc',
'đồ chết không ai hay',
'đồ chết không ai biết',
'đồ chết cô đơn',
'đồ chết một mình',
'đồ chết bờ chết bụi',
'đồ chết đường chết chợ',
'đồ chết đói',
'đồ chết khát',
'đồ chết rét',
'đồ chết nóng',
'đồ chết vì ngu',
'đồ chết vì tham',
'đồ chết vì gái',
'đồ chết vì trai',
'đồ chết vì tiền',
'đồ chết vì danh',
'đồ chết vì lợi',
'đồ chết vì tình',
'đồ chết vì nhục',
'đồ chết vì hận',
'đồ chết vì oan',
'đồ chết oan',
'đồ chết ức',
'đồ chết không nhắm mắt',
'đồ chết không siêu thoát',
'đồ chết làm ma đói',
'đồ chết làm ma lang thang',
'đồ chết đầu thai làm chó',
'đồ chết đầu thai làm lợn',
'đồ chết đầu thai làm súc sinh',
'đồ kiếp chó',
'đồ kiếp lợn',
'đồ kiếp trâu ngựa',
'đồ kiếp tôi đòi',
'đồ kiếp nô lệ',
'đồ kiếp con ở',
'đồ kiếp đày tớ',
'đồ kiếp làm thuê',
'đồ kiếp nghèo hèn',
'đồ kiếp bần cùng',
'đồ kiếp khốn khổ',
'đồ kiếp bất hạnh',
'đồ kiếp bi thảm',
'đồ kiếp đọa đày',
'đồ kiếp truân chuyên',
'đồ kiếp long đong',
'đồ kiếp lận đận',
'đồ kiếp ba chìm bảy nổi',
'đồ sống không bằng chết',
'đồ sống dở chết dở',
'đồ sống thừa',
'đồ sống chật đất',
'đồ sống tốn cơm',
'đồ sống làm khổ người khác',
'đồ sống không có ích',
'đồ sống không có mục đích',
'đồ sống không có lý tưởng',
'đồ sống không có tương lai',
'đồ sống như một cái bóng',
'đồ sống như một con ma',
'đồ sống như một cái xác không hồn',
'đồ sống mà như đã chết',
'thằng mặt lồn',
'con mặt lồn',
'đồ mặt buồi',
'đồ mặt cặc',
'thằng mặt buồi',
'thằng mặt cặc',
'con mặt lồn',
'con mặt cặc',
'cái lồn của mẹ mày',
'cái cặc của cha mày',
'lồn thối',
'lồn rộng',
'lồn nát',
'lồn già',
'lồn trâu',
'cặc bé',
'cặc ngắn',
'cặc non',
'cặc thối',
'cặc điếc',
'buồi ngắn',
'buồi nhỏ',
'buồi mềm',
'buồi thối',
'buồi thúi',
'dái lép',
'dái xệ',
'dái thâm',
'dái nhăn nheo',
'địt thối lồn',
'địt nát lồn',
'địt rách lồn',
'địt bung lồn',
'địt lòi lồn',
'địt sưng lồn',
'địt lủng lồn',
'địt chết mẹ mày',
'đụ chết cha mày',
'làm tình với mẹ mày',
'chịch mẹ mày',
'xoạc mẹ mày',
'phịch mẹ mày',
'nện mẹ mày',
'giã mẹ mày',
'đóng mẹ mày',
'đâm mẹ mày',
'thọc mẹ mày',
'chơi mẹ mày',
'xơi mẹ mày',
'ăn mẹ mày',
'húp mẹ mày',
'liếm lồn mẹ mày',
'bú cặc cha mày',
'mút dái ông nội mày',
'vét máng',
'chăn rau',
'lái máy bay',
'đồ phi công',
'thằng phi công',
'đồ máy bay bà già',
'con máy bay bà già',
'đồ trâu già gặm cỏ non',
'đồ bà già ham trai trẻ',
'đồ ông già ham gái trẻ',
'đồ già mất nết',
'đồ già không nên nết',
'đồ già dê',
'đồ già khú đế',
'đồ già hàm',
'đồ già lẩm cẩm',
'đồ già lú lẫn',
'đồ già đãng trí',
'đồ già sắp chết',
'đồ già gần đất xa trời',
'đồ già xuống lỗ',
'đồ già không có con cháu',
'đồ già cô độc',
'đồ già neo đơn',
'đồ già khốn khổ',
'đồ vô phúc',
'đồ thất đức',
'đồ ác đức',
'đồ thất nhân tâm',
'đồ lòng dạ hiểm độc',
'đồ lòng dạ đàn bà',
'đồ bụng dạ hẹp hòi',
'đồ bụng dạ khó lường',
'đồ bụng một bồ dao găm',
'đồ tâm địa độc ác',
'đồ tâm địa xấu xa',
'đồ tâm địa đen tối',
'đồ tâm địa bất chính',
'đồ tâm địa gian manh',
'đồ tâm địa xảo quyệt',
'đồ tâm cơ',
'con tâm cơ',
'đồ mưu mô',
'đồ mưu hèn kế bẩn',
'đồ thủ đoạn',
'đồ lắm chiêu nhiều trò',
'đồ diễn viên',
'đồ kịch sĩ',
'đồ diễn sâu',
'đồ đóng kịch',
'đồ giả vờ',
'đồ giả nai',
'con giả nai',
'đồ thảo mai',
'con thảo mai',
'đồ xạo lồn',
'con xạo lồn',
'thằng xạo lồn',
'đồ xạo cặc',
'thằng xạo cặc',
'đồ xạo ke',
'đồ nổ',
'đồ chém gió',
'đồ phét lác',
'đồ khoác lác',
'đồ khoe khoang',
'đồ khoe của',
'đồ trọc phú',
'đồ trưởng giả học làm sang',
'đồ học làm sang',
'đồ đú bẩn',
'đồ đú trend',
'đồ a dua đòi đú',
'đồ đú đởn',
'con đú đởn',
'đồ lẳng lơ',
'con lẳng lơ',
'đồ chưng diện',
'đồ làm dáng',
'đồ điệu đà',
'con điệu đà',
'đồ đỏm dáng',
'con đỏm dáng',
'đồ công tử',
'đồ tiểu thư',
'đồ lá ngọc cành vàng',
'đồ con vua cháu chúa',
'đồ hoàng thân quốc thích',
'đồ dòng dõi trâm anh',
'đồ quý tộc rởm',
'đồ sang chảnh rởm',
'đồ thượng lưu rởm',
'đồ trí thức rởm',
'đồ đạo đức giả',
'đồ thánh nữ',
'con thánh nữ',
'đồ quân tử rởm',
'thằng quân tử rởm',
'đồ anh hùng rơm',
'thằng anh hùng rơm',
'đồ thùng rỗng kêu to',
'đồ không có thực tài',
'đồ bất tài vô dụng',
'đồ chỉ được cái mồm',
'đồ nói hay làm dở',
'đồ nói một đằng làm một nẻo',
'đồ nói không giữ lời',
'đồ thất hứa',
'đồ không đáng tin',
'đồ lật mặt',
'đồ trở mặt',
'đồ ăn cháo đái bát',
'đồ nuôi ong tay áo',
'đồ nuôi khỉ dòm nhà',
'đồ cõng rắn cắn gà nhà',
'đồ rước voi về giày mả tổ',
'đồ ngu xuẩn',
'đồ đần độn',
'đồ đần',
'đồ đần thối',
'đồ đần có đẳng cấp',
'đồ ngẫn',
'đồ ngáo',
'đồ khờ',
'đồ khờ khạo',
'đồ khờ như nai',
'đồ ngu si',
'đồ ngu si đần độn',
'đồ ngu si tứ chi phát triển',
'đồ đầu óc ngu si tứ chi phát triển',
'đồ não úng thủy',
'đồ não có vấn đề',
'đồ não bị chập',
'đồ não bị lỗi',
'đồ não đi du lịch',
'đồ não để trong tủ lạnh',
'đồ não để quên ở nhà',
'đồ não ngắn không quá một nếp nhăn',
'đồ không có não để suy nghĩ',
'đồ dùng đầu gối để suy nghĩ',
'đồ dùng chân để suy nghĩ',
'đồ dùng đít để suy nghĩ',
'đồ suy nghĩ bằng đầu buồi',
'thằng suy nghĩ bằng đầu buồi',
'đồ suy nghĩ bằng cái lồn',
'con suy nghĩ bằng cái lồn',
'đồ đầu chỉ để mọc tóc',
'đồ đầu chỉ để trang trí',
'đồ đầu to óc bằng quả nho',
'đồ xác to óc bằng hạt tiêu',
'đồ to xác',
'đồ to đầu',
'đồ to mồm',
'đồ to gan',
'đồ to gan lớn mật',
'đồ gan hùm',
'đồ gan cóc tía',
'đồ liều mạng',
'đồ liều lĩnh',
'đồ coi trời bằng vung',
'đồ coi thường pháp luật',
'đồ chống đối',
'đồ phản động',
'đồ ba sọc',
'đồ ba que',
'đồ bán nước hại dân',
'đồ tay sai cho ngoại bang',
'đồ bợ đít',
'đồ liếm gót',
'đồ liếm đít',
'đồ nịnh bợ',
'đồ nịnh hót',
'đồ bợ đỡ',
'đồ xu nịnh',
'đồ chó săn của tư bản',
'đồ tư bản giãy chết',
'đồ đế quốc',
'đồ thực dân',
'đồ phong kiến',
'đồ lạc hậu',
'đồ trì trệ',
'đồ chậm tiến',
'đồ bảo thủ',
'đồ cản đường',
'đồ ngáng đường',
'đồ phá đám',
'đồ phá hoại',
'đồ phá làng phá xóm',
'đồ phá hoại của công',
'đồ phá hoại tài sản quốc gia',
'đồ phá hoại môi trường',
'đồ vô trách nhiệm',
'đồ thiếu trách nhiệm',
'đồ thiếu ý thức cộng đồng',
'đồ sống chỉ biết mình',
'đồ ích kỷ hẹp hòi',
'đồ cá nhân',
'đồ chỉ nghĩ cho bản thân',
'đồ không nghĩ cho người khác',
'đồ vô tâm',
'đồ vô tình',
'đồ máu lạnh',
'đồ máu lạnh vô tình',
'đồ không có trái tim',
'đồ trái tim sắt đá',
'đồ trái tim băng giá',
'đồ không có tình người',
'đồ không có nhân tính',
'đồ mất hết nhân tính',
'đồ thú vật',
'đồ không bằng con thú',
'đồ chó còn hơn',
'đồ lợn còn hơn',
'đồ súc vật còn hơn',
'đồ không đáng làm người',
'đồ không xứng đáng làm người',
'đồ không được làm người',
'đồ nên chết đi',
'đồ nên biến mất khỏi thế giới này',
'đồ không nên tồn tại',
'đồ sự tồn tại của mày là một sai lầm',
'đồ là một nỗi ô nhục',
'đồ là một vết nhơ',
'đồ là một sự sỉ nhục',
'đồ làm xấu mặt gia đình',
'đồ làm ô uế dòng họ',
'đồ làm nhục quốc thể',
'đồ làm người khác phải xấu hổ',
'đồ không biết xấu hổ',
'đồ không biết nhục',
'đồ không biết ngượng',
'đồ mặt dày hơn cả mo cau',
'đồ mặt dày như thớt',
'đồ mặt trơ trán bóng',
'đồ da mặt dày',
'đồ không có lòng tự trọng',
'đồ chà đạp lên lòng tự trọng của người khác',
'đồ coi thường người khác',
'đồ khinh người',
'đồ miệt thị',
'đồ phân biệt đối xử',
'đồ phân biệt chủng tộc',
'đồ phân biệt vùng miền',
'đồ kỳ thị',
'đồ kỳ thị giới tính',
'đồ kỳ thị người đồng tính',
'đồ kỳ thị người khuyết tật',
'đồ kỳ thị người nghèo',
'đồ kỳ thị người dân tộc thiểu số',
'đồ ác ý',
'đồ có ác ý',
'đồ có ý đồ xấu',
'đồ có âm mưu',
'đồ mưu đồ bất chính',
'đồ mưu đồ đen tối',
'đồ có dã tâm',
'đồ có tham vọng',
'đồ có lòng tham không đáy',
'đồ tham lam vô độ',
'đồ tham lam ích kỷ',
'đồ tham lam mù quáng',
'đồ tham sân si',
'đồ bị đồng tiền làm mờ mắt',
'đồ nô lệ của đồng tiền',
'đồ bán mình vì tiền',
'đồ bán rẻ danh dự',
'đồ bán rẻ nhân phẩm',
'đồ bán rẻ linh hồn cho quỷ dữ',
'đồ con quỷ',
'đồ quỷ đội lốt người',
'đồ ma vương',
'đồ sa tăng',
'đồ địa ngục',
'đồ âm phủ',
'đồ ma trơi',
'đồ cô hồn',
'đồ cô hồn các đảng',
'đồ cô hồn sống',
'đồ ăn mày',
'đồ ăn xin',
'đồ ăn bám',
'đồ ăn chực',
'đồ ăn chùa',
'đồ ăn ké',
'đồ ăn mảnh',
'đồ ăn gian',
'đồ ăn lận',
'đồ ăn bớt ăn xén',
'đồ ăn trên đầu trên cổ người khác',
'đồ hút máu người',
'đồ bóc lột',
'đồ tư bản bóc lột',
'đồ địa chủ',
'đồ cường hào ác bá',
'đồ hà hiếp dân lành',
'đồ ức hiếp kẻ yếu',
'đồ bắt nạt',
'đồ bắt nạt người mới',
'đồ bắt nạt người yếu thế',
'đồ ma cũ bắt nạt ma mới',
'đồ lấy thịt đè người',
'đồ cậy mạnh hiếp yếu',
'đồ cậy quyền cậy thế',
'đồ cậy chức cậy quyền',
'đồ lạm dụng chức quyền',
'đồ lạm dụng quyền lực',
'đồ lạm dụng tình dục',
'đồ quấy rối tình dục',
'đồ xâm hại tình dục',
'đồ hiếp dâm',
'thằng hiếp dâm',
'đồ ấu dâm',
'thằng ấu dâm',
'đồ loạn luân',
'đồ bạo hành',
'đồ bạo hành gia đình',
'đồ bạo hành trẻ em',
'đồ bạo hành phụ nữ',
'đồ bạo hành động vật',
'đồ vũ phu',
'thằng vũ phu',
'đồ đánh vợ',
'thằng đánh vợ',
'đồ đánh con',
'đồ đánh người già',
'đồ bất kính với người lớn tuổi',
'đồ láo với người già',
'đồ hỗn với cha mẹ',
'đồ cãi cha cãi mẹ',
'đồ cãi thầy',
'đồ cãi sếp',
'đồ cãi cố',
'đồ cãi chày cãi cối',
'đồ cãi cùn',
'đồ lý sự cùn',
'đồ nói ngang',
'đồ nói ngược',
'đồ nói bừa',
'đồ nói bậy',
'đồ nói bạ',
'đồ nói nhăng nói cuội',
'đồ nói phét',
'đồ nói dóc',
'đồ nói láo',
'đồ nói điêu',
'đồ nói xạo',
'đồ nói dối không chớp mắt',
'đồ nói dối như cuội',
'đồ lươn lẹo',
'đồ trơn như lươn',
'đồ khôn lỏi',
'đồ khôn vặt',
'đồ khôn nhà dại chợ',
'đồ thùng rỗng kêu to',
'đồ không biết thì dựa cột mà nghe',
'đồ không biết điều',
'đồ không biết trên biết dưới',
'đồ không biết phải trái',
'đồ không biết đúng sai',
'đồ không phân biệt được phải trái',
'đồ lẫn lộn trắng đen',
'đồ đổi trắng thay đen',
'đồ lật lọng',
'đồ lật kèo',
'đồ nuốt lời',
'đồ hứa suông',
'đồ hứa lèo',
'đồ không giữ chữ tín',
'đồ bội tín',
'đồ bội ước',
'đồ vi phạm hợp đồng',
'đồ vi phạm pháp luật',
'đồ vi phạm đạo đức',
'đồ vi phạm quy tắc',
'đồ vi phạm nội quy',
'đồ sống không có nguyên tắc',
'đồ sống buông thả',
'đồ sống bừa bãi',
'đồ sống cẩu thả',
'đồ ở bẩn',
'đồ ở dơ',
'đồ lôi thôi',
'đồ lếch thếch',
'đồ luộm thuộm',
'đồ nhếch nhác',
'đồ bẩn thỉu',
'đồ hôi hám',
'đồ hôi nách',
'đồ hôi chân',
'đồ hôi miệng',
'đồ ở bẩn như lợn',
'đồ ăn ở bẩn thỉu',
'đồ ăn ở không có đức',
'đồ thất đức vô phúc',
'đồ ăn ở ác',
'đồ gieo gió gặt bão',
'đồ tự rước họa',
'đồ tự đào hố chôn mình',
'đồ tự sát',
'đồ tự tử',
'đồ tự hủy hoại bản thân',
'đồ tự ti',
'đồ mặc cảm',
'đồ tự kỷ ám thị',
'đồ sống nội tâm',
'đồ sống khép kín',
'đồ khó gần',
'đồ khó ở',
'đồ khó tính',
'đồ khó chiều',
'đồ khó chịu',
'đồ khó ưa',
'đồ đáng ghét',
'đồ đáng khinh',
'đồ đáng khinh bỉ',
'đồ đáng nguyền rủa',
'đồ đáng bị trừng phạt',
'đồ đáng bị nguyền rủa',
'đồ đáng bị trời phạt',
'đồ đáng bị sét đánh',
'đồ đáng bị quả báo',
'đồ đáng bị nghiệp quật',
'đồ đáng bị xa lánh',
'đồ đáng bị tẩy chay',
'đồ đáng bị cô lập',
'đồ đáng bị phỉ nhổ',
'đồ đáng bị ném đá',
'đồ đáng bị chửi rủa',
'đồ đáng bị đày xuống địa ngục',
'đồ 18 tầng địa ngục',
'đồ dầu sôi lửa bỏng',
'đồ bị quỷ sứ hành hạ',
'đồ bị ma ám',
'đồ bị quỷ ám',
'đồ bị nguyền rủa',
'đồ bị trù ẻo',
'đồ bị bỏ bùa',
'đồ bị chơi ngải',
'đồ bị thư yếm',
'đồ bị ma làm',
'đồ bị ma nhập',
'đồ bị vong theo',
'đồ có vong theo',
'đồ có ma ám',
'đồ nhà có ma',
'đồ đất có ma',
'đồ xui xẻo',
'đồ đen như mõm chó',
'đồ nhọ như đít nồi',
'đồ số con rệp',
'đồ tận số',
'đồ hết thời',
'đồ hết phước',
'đồ vô phước',
'đồ bạc phước',
'đồ bạc mệnh',
'đồ hồng nhan bạc mệnh',
'đồ tài hoa bạc mệnh',
'đồ yểu mệnh',
'đồ chết non',
'đồ chết yểu',
'đồ đoản mệnh',
'đồ chết sớm',
'đồ chết không đáng',
'đồ chết oan uổng',
'đồ chết tức tưởi',
'đồ chết thảm',
'đồ chết thê thảm',
'đồ chết bi thảm',
'đồ chết đau đớn',
'đồ chết trong cô độc',
'đồ chết trong ân hận',
'đồ chết trong nuối tiếc',
'đồ chết trong tủi nhục',
'đồ chết trong ô nhục',
'đồ chết trong danh dự',
'đồ chết vinh quang',
'đồ chết vì nước',
'đồ chết vì dân',
'đồ liệt sĩ',
'đồ anh hùng',
'đồ anh hùng rơm',
'đồ dỏm',
'đồ giả',
'đồ fake',
'đồ nhái',
'đồ đạo nhái',
'đồ copy',
'đồ ăn cắp chất xám',
'đồ ăn cắp ý tưởng',
'đồ ăn cắp bản quyền',
'đồ vi phạm bản quyền',
'đồ sử dụng lậu',
'đồ xài chùa',
'đồ xem chùa',
'đồ nghe chùa',
'đồ đọc chùa',
'đồ chùa',
'đồ miễn phí',
'đồ free',
'đồ rẻ tiền',
'đồ hạ cấp',
'đồ thấp kém',
'đồ kém cỏi',
'đồ kém sang',
'đồ bần',
'đồ phèn',
'đồ quê',
'đồ hai lúa',
'đồ nhà quê ra tỉnh',
'đồ tỉnh lẻ',
'đồ dân tỉnh',
'đồ nhà quê học đòi làm sang',
'đồ trọc phú khoe của',
'đồ khoe mẽ',
'đồ khoe thân',
'con khoe thân',
'đồ khoe hàng',
'con khoe hàng',
'đồ khoe vú',
'con khoe vú',
'đồ khoe mông',
'con khoe mông',
'đồ khoe lồn',
'con khoe lồn',
'đồ khoe cặc',
'thằng khoe cặc',
'đồ lộ hàng',
'con lộ hàng',
'đồ hở hang',
'con hở hang',
'đồ ăn mặc hở hang',
'con ăn mặc hở hang',
'đồ ăn mặc thiếu vải',
'con ăn mặc thiếu vải',
'đồ ăn mặc phản cảm',
'con ăn mặc phản cảm',
'đồ ăn mặc lố lăng',
'con ăn mặc lố lăng',
'đồ ăn mặc kệch cỡm',
'con ăn mặc kệch cỡm',
'đồ không có gu thẩm mỹ',
'đồ thẩm mỹ lỗi',
'đồ phẫu thuật thẩm mỹ hỏng',
'đồ mặt nhựa',
'con mặt nhựa',
'đồ mặt đơ',
'con mặt đơ',
'đồ mặt rắn',
'con mặt rắn',
'đồ mặt dao kéo',
'con mặt dao kéo',
'đồ đẹp nhân tạo',
'đồ đẹp giả',
'đồ đẹp không tự nhiên',
'đồ xấu tự nhiên',
'đồ xấu bền vững',
'đồ xấu kinh niên',
'đồ xấu gia truyền',
'đồ xấu từ trong trứng',
'đồ xấu không góc chết',
'đồ xấu toàn diện',
'đồ xấu từ đầu đến chân',
'đồ xấu không có chỗ nào đẹp',
'đồ xấu không thể cứu vãn',
'đồ xấu không cần phấn son',
'đồ xấu không cần photoshop',
'đồ xấu một cách tự nhiên',
'đồ xấu một cách chân thật',
'đồ xấu một cách mộc mạc',
'đồ xấu một cách giản dị',
'đồ xấu một cách đáng yêu',
'đồ xấu một cách duyên dáng',
'đồ xấu một cách hài hước',
'đồ xấu một cách độc lạ',
'đồ xấu một cách khác biệt',
'đồ xấu một cách ấn tượng',
'đồ xấu một cách khó quên',
'đồ xấu đi vào lòng đất',
'đồ xấu đi vào lịch sử',
'đồ xấu đi vào huyền thoại',
'đồ xấu đi vào thơ ca',
'đồ xấu đi vào âm nhạc',
'đồ xấu đi vào hội họa',
'đồ xấu đi vào điện ảnh',
'đồ xấu là một nghệ thuật',
'đồ người xấu là một nghệ sĩ',
'đồ xấu nhưng biết phấn đấu',
'đồ xấu nhưng có duyên',
'đồ xấu nhưng kết cấu đẹp',
'đồ xấu nhưng được cái nết',
'đồ xấu người đẹp nết',
'đồ tốt gỗ hơn tốt nước sơn',
'đồ cái nết đánh chết cái đẹp',
'đồ đẹp đẽ khoe ra xấu xa đậy lại',
'đồ đẹp nhân tạo còn hơn xấu tự nhiên',
'đồ không có phụ nữ xấu',
'đồ chỉ có phụ nữ không biết làm đẹp',
'đồ đẹp vì lụa',
'đồ lúa tốt vì phân',
'đồ người đẹp vì lụa',
'đồ lúa tốt vì phân',
'đồ chó đẹp vì lông',
'đồ gà đẹp vì mã',
'đồ người đẹp vì tiền',
'đồ người đẹp vì quyền',
'đồ người đẹp vì photoshop',
'đồ người đẹp vì app',
'đồ sống ảo tung chảo',
'đồ sống ảo lòi',
'đồ sống ảo không có thật',
'đồ sống ảo khác xa đời thực',
'đồ trên mạng và ngoài đời là hai người khác nhau',
'đồ lừa dối',
'đồ lừa lọc',
'đồ lừa tình lừa tiền',
'đồ lừa đảo chuyên nghiệp',
'đồ lừa đảo có tổ chức',
'đồ lừa đảo xuyên quốc gia',
'đồ tội phạm công nghệ cao',
'đồ hacker',
'đồ cracker',
'đồ spammer',
'đồ scamer',
'đồ lừa đảo qua mạng',
'đồ lừa đảo qua điện thoại',
'đồ lừa đảo trúng thưởng',
'đồ lừa đảo tuyển dụng',
'đồ lừa đảo tình cảm',
'đồ lừa đảo từ thiện',
'đồ lừa đảo đa cấp',
'đồ bán hàng đa cấp',
'đồ đa cấp biến tướng',
'đồ làm giàu không khó',
'đồ việc nhẹ lương cao',
'đồ làm tại nhà',
'đồ làm online',
'đồ không cần bằng cấp',
'đồ không cần kinh nghiệm',
'đồ không cần vốn',
'đồ chỉ cần chăm chỉ',
'đồ chỉ cần kiên trì',
'đồ chỉ cần tin tưởng',
'đồ chỉ cần nghe lời',
'đồ chỉ cần làm theo',
'đồ chỉ cần copy paste',
'đồ chỉ cần chia sẻ',
'đồ chỉ cần mời bạn bè',
'đồ chỉ cần tuyển dụng',
'đồ chỉ cần xây dựng hệ thống',
'đồ chỉ cần ngồi chơi xơi nước',
'đồ chỉ cần hưởng thụ',
'đồ chỉ cần đi du lịch',
'đồ chỉ cần khoe tiền',
'đồ chỉ cần khoe xe',
'đồ chỉ cần khoe nhà',
'đồ chỉ cần khoe thành công',
'đồ chỉ cần khoe hạnh phúc',
'đồ chỉ cần khoe gia đình',
'đồ chỉ cần khoe con cái',
'đồ chỉ cần khoe chồng',
'đồ chỉ cần khoe vợ',
'đồ chỉ cần khoe người yêu',
'đồ chỉ cần khoe bồ',
'đồ chỉ cần khoe nhân tình',
'đồ chỉ cần khoe Tuesday',
'đồ chỉ cần khoe con giáp thứ 13',
'đồ kẻ thứ ba',
'đồ người thứ ba',
'đồ chen chân vào hạnh phúc người khác',
'đồ phá hoại gia đình người khác',
'đồ cướp chồng',
'con cướp chồng',
'đồ cướp vợ',
'thằng cướp vợ',
'đồ cướp người yêu',
'đồ tiểu tam',
'con tiểu tam',
'đồ trà xanh',
'con trà xanh',
'đồ phò',
'con phò',
'đồ đĩ',
'con đĩ',
'đồ đi khách',
'con đi khách',
'đồ làm gái',
'con làm gái',
'đồ bán dâm',
'con bán dâm',
'đồ bán thân',
'con bán thân',
'đồ bán hoa',
'con bán hoa',
'đồ bán phấn buôn hương',
'con bán phấn buôn hương',
'đồ gái gọi',
'con gái gọi',
'đồ gái bao',
'con gái bao',
'đồ gái làng chơi',
'con gái làng chơi',
'đồ gái đứng đường',
'con gái đứng đường',
'đồ gái làm tiền',
'con gái làm tiền',
'đồ gái mại dâm',
'con gái mại dâm',
'đồ cave',
'con cave',
'đồ kỹ nữ',
'con kỹ nữ',
'đồ thanh lâu',
'con thanh lâu',
'đồ lầu xanh',
'con lầu xanh',
'đồ gái điếm',
'con gái điếm',
'đồ gái gú',
'đồ trai bao',
'thằng trai bao',
'đồ trai gọi',
'thằng trai gọi',
'đồ trai đứng đường',
'thằng trai đứng đường',
'đồ trai làm tiền',
'thằng trai làm tiền',
'đồ trai mại dâm',
'thằng trai mại dâm',
'đồ trai bao cao cấp',
'thằng trai bao cao cấp',
'đồ trai bao hạng sang',
'thằng trai bao hạng sang',
'đồ trai bao cho quý bà',
'thằng trai bao cho quý bà',
'đồ trai bao cho người đồng tính',
'thằng trai bao cho người đồng tính',
'đồ trai bao cho người nước ngoài',
'thằng trai bao cho người nước ngoài',
'đồ trai bao sinh viên',
'thằng trai bao sinh viên',
'đồ trai bao công nhân',
'thằng trai bao công nhân',
'đồ trai bao trí thức',
'thằng trai bao trí thức',
'đồ trai bao nghệ sĩ',
'thằng trai bao nghệ sĩ',
'đồ trai bao người mẫu',
'thằng trai bao người mẫu',
'đồ trai bao diễn viên',
'thằng trai bao diễn viên',
'đồ trai bao ca sĩ',
'thằng trai bao ca sĩ',
'đồ trai bao cầu thủ',
'thằng trai bao cầu thủ',
'đồ trai bao công an',
'thằng trai bao công an',
'đồ trai bao bộ đội',
'thằng trai bao bộ đội',
'đồ trai bao bác sĩ',
'thằng trai bao bác sĩ',
'đồ trai bao giáo viên',
'thằng trai bao giáo viên',
'đồ trai bao công chức',
'thằng trai bao công chức',
'đồ trai bao doanh nhân',
'thằng trai bao doanh nhân',
'đồ trai bao giám đốc',
'thằng trai bao giám đốc',
'đồ trai bao chủ tịch',
'thằng trai bao chủ tịch',
'đồ trai bao tổng giám đốc',
'thằng trai bao tổng giám đốc',
'đồ trai bao chính trị gia',
'thằng trai bao chính trị gia',
'đồ trai bao quan chức',
'thằng trai bao quan chức',
'đồ trai bao có vợ',
'thằng trai bao có vợ',
'đồ trai bao có người yêu',
'thằng trai bao có người yêu',
'đồ trai bao có con',
'thằng trai bao có con',
'đồ trai bao có gia đình',
'thằng trai bao có gia đình',
'đồ trai bao có học thức',
'thằng trai bao có học thức',
'đồ trai bao có địa vị',
'thằng trai bao có địa vị',
'đồ trai bao có tiền',
'thằng trai bao có tiền',
'đồ trai bao có quyền',
'thằng trai bao có quyền',
'đồ trai bao có danh',
'thằng trai bao có danh',
'đồ trai bao có tiếng',
'thằng trai bao có tiếng',
'đồ trai bao có tài',
'thằng trai bao có tài',
'đồ trai bao có sắc',
'thằng trai bao có sắc',
'đồ trai bao có duyên',
'thằng trai bao có duyên',
'đồ trai bao có tâm',
'thằng trai bao có tâm',
'đồ trai bao có đức',
'thằng trai bao có đức',
'đồ trai bao có tình',
'thằng trai bao có tình',
'đồ trai bao có nghĩa',
'thằng trai bao có nghĩa',
'đồ trai bao có hiếu',
'thằng trai bao có hiếu',
'đồ trai bao có trung',
'thằng trai bao có trung',
'đồ trai bao có tín',
'thằng trai bao có tín',
'đồ trai bao có nhân',
'thằng trai bao có nhân',
'đồ trai bao có lễ',
'thằng trai bao có lễ',
'đồ trai bao có trí',
'thằng trai bao có trí',
'đồ trai bao có dũng',
'thằng trai bao có dũng',
'đồ trai bao có liêm',
'thằng trai bao có liêm',
'đồ trai bao có sỉ',
'thằng trai bao có sỉ',
'đồ trai bao hoàn hảo',
'thằng trai bao hoàn hảo',
'đồ trai bao tuyệt vời',
'thằng trai bao tuyệt vời',
'đồ trai bao trong mơ',
'thằng trai bao trong mơ',
'đồ trai bao lý tưởng',
'thằng trai bao lý tưởng',
'đồ trai bao quốc dân',
'thằng trai bao quốc dân',
'đồ trai bao của mọi nhà',
'thằng trai bao của mọi nhà',
'đồ trai bao của công chúng',
'thằng trai bao của công chúng',
'đồ trai bao của xã hội',
'thằng trai bao của xã hội',
'đồ trai bao của nhân loại',
'thằng trai bao của nhân loại',
'đồ trai bao của vũ trụ',
'thằng trai bao của vũ trụ',
'đồ trai bao của thiên hà',
'thằng trai bao của thiên hà',
'đồ trai bao của đa vũ trụ',
'thằng trai bao của đa vũ trụ',
'đồ trai bao của mọi thời đại',
'thằng trai bao của mọi thời đại',

  'fuck you',
  'shit',
  'bitch',
  'asshole',
  'bastard',
  'damn',
  'cunt',
  'dickhead',
  'motherfucker',
  'piss off',
  'crap',
  'bloody',
  'bugger',
  'git',
  'minger',
  'cocksucker',
  'faggot',
  'nigger',
  'twat',
  'whore',
  // Note: Japanese profanity is highly contextual.'

  'baka', // ばか - stupid'
  'aho', // あほ - idiot, moron'
  'kuso', // くそ - shit, damn'
  'shine', // 死ね - die'
  'kono yarou', // この野郎 - you bastard'
  'chikushou', // ちくしょう - damn it, son of a bitch'
  'urusai', // うるさい - shut up, noisy'
  'busu', // ぶす - ugly woman'
  'kimoi', // きもい - gross, disgusting'

  // Mild'
  'hetakuso', // へたくそ - clumsy, unskillful'
  'uzai', // うざい - annoying, pain in the ass'
  'dasai', // ださい - uncool, unfashionable'

  // Strong'
  'kutabare', // くたばれ - go to hell, drop dead'
  'temee', // てめえ - a very rude way of saying "you"'
  'kisama', // 貴様 - a very rude and confrontational way of saying "you"'
  'kusokurae', // くそくらえ - eat shit'
  'banshi ni atai suru', // 万死に値する - you deserve to die a thousand deaths'
  // --- Chinese ---'

  // Core Profanity & Phrases'
  '操', // cào - fuck'
  '肏', // cào - fuck (variant)'
  '干', // gàn - fuck (common alternative)'
  '日', // rì - fuck (slang)'
  '妈的', // mā de - damn it'
  '他妈的', // tā mā de - fucking...'
  'tmd', // abbreviation for 他妈的'
  '靠', // kào - damn/fuck (milder)'
  '逼', // bī - cunt'
  '屄', // bī - cunt (variant)'
  '傻逼', // shǎ bī - fucking idiot'
  'sb', // abbreviation for 傻逼'
  '煞笔', // shā bǐ - homophone for 傻逼'
  '装逼', // zhuāng bī - to be a pretentious douche'
  '操你妈', // cāo nǐ mā - fuck your mother'
  'cnm', // abbreviation for 操你妈'
  '草泥马', // cǎo ní mǎ - homophone for 操你妈 (lit. grass mud horse)'
  '我操', // wǒ cào - holy fuck'
  '卧槽', // wò cáo - homophone for 我操'
  '尼玛', // ní mǎ - homophone for 你妈 (your mom)'
  '你妈死了', // nǐ mā sǐ le - your mom is dead (curse)'
  'nmsl', // abbreviation for 你妈死了'

  // General Insults'
  '滚', // gǔn - fuck off / get lost'
  '混蛋', // hún dàn - bastard'
  '王八蛋', // wáng bā dàn - bastard / son of a bitch'
  '笨蛋', // bèn dàn - idiot'
  '白痴', // bái chī - moron'
  '废物', // fèi wù - useless person / trash'
  '垃圾', // lā jī - garbage / trash'
  '杂种', // zá zhǒng - bastard / mongrel'
  '畜生', // chù shēng - beast (dehumanizing)'
  '贱人', // jiàn rén - bitch / despicable person'
  '婊子', // biǎo zi - whore'
  '变态', // biàn tài - pervert'
];